### ISSUE TITLE
Right-to-left languages

### ISSUE THREAD

**Issue by benbro** [webodf/WebODF#186]
This is a feature request to add support for right-to-left languages.

The align buttons are aligning the paragraph borders but not the text.
In Word and LibreOffice the align buttons are equivalent text-align in CSS.

Text direction left/right buttons are missing.
In Word and LibreOffice the text direction buttons are equivalent to "direction: rtl" in CSS.

What is involved in adding support for RTL?
Is it just styling or does the engine needs to be aware of the direction of letters?

Maybe CodeMirror's RTL support could be relevant?
https://github.com/marijnh/CodeMirror/issues/294

Thanks

**Comment by amir110** [comment]
yes very very important

**Comment by heshamz** [comment]
Is there any plan to implement this feature?
