### ISSUE TITLE
WebODF on local machine

### ISSUE THREAD

**Issue by tretom2121** [webodf/WebODF#935]
I want to use WebODF in it's simplest form: http://www.webodf.org/start/ Just to show an ODT document in a webbrowser. 
I have the followings in the same local folder (c:\Data): 
- webODTTest.html 
- Try.odt 
- webodf.js

the ODTTest.html looks like the one in the link above.
When I try to load the html in a browser, the script seems to start, because it shows: "LoadingTry.odt...". But then at this point it stops, and doesn't load/show the Try.odt.

What am I missing?

**Comment by vandenoever** [comment]
You'll need to run from a (small) web server. WebODF uses XMLHttpRequest which does not work on file://
